// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-sTltNEOetUVSvqDhR5YpzUwJVKP0WsA',
    appId: '1:640450823915:web:a50de0a4af749121e360ae',
    messagingSenderId: '640450823915',
    projectId: 'vamos-fffa4',
    authDomain: 'vamos-fffa4.firebaseapp.com',
    storageBucket: 'vamos-fffa4.firebasestorage.app',
    measurementId: 'G-VE1HBCND9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrYt3AsH85RBWWKfTXAUkmR-mP1899Pv4',
    appId: '1:640450823915:android:a8afb4abae38fb14e360ae',
    messagingSenderId: '640450823915',
    projectId: 'vamos-fffa4',
    storageBucket: 'vamos-fffa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQTqRswcT7ELp0h6rim55PKDlDPnHZ6gY',
    appId: '1:640450823915:ios:41ae5c4ecc7ddc4be360ae',
    messagingSenderId: '640450823915',
    projectId: 'vamos-fffa4',
    storageBucket: 'vamos-fffa4.firebasestorage.app',
    iosBundleId: 'com.example.flashcardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQTqRswcT7ELp0h6rim55PKDlDPnHZ6gY',
    appId: '1:640450823915:ios:41ae5c4ecc7ddc4be360ae',
    messagingSenderId: '640450823915',
    projectId: 'vamos-fffa4',
    storageBucket: 'vamos-fffa4.firebasestorage.app',
    iosBundleId: 'com.example.flashcardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-sTltNEOetUVSvqDhR5YpzUwJVKP0WsA',
    appId: '1:640450823915:web:01ace8475465be91e360ae',
    messagingSenderId: '640450823915',
    projectId: 'vamos-fffa4',
    authDomain: 'vamos-fffa4.firebaseapp.com',
    storageBucket: 'vamos-fffa4.firebasestorage.app',
    measurementId: 'G-X3F8X3PWWT',
  );
}
